name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      run: |
        git config user.name "${{ secrets.GITHUB_ACTOR }}"
        git config user.email "${{ secrets.GITHUB_ACTOR }}@users.noreply.github.com"
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push "https://${{ secrets.GITHUB_ACTOR }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" main:main
